package = "luxdummy2"
version = "0.1.4"
lua = ">=5.1"

[description]
summary = ""
maintainer = "rodamaral"
labels = [ "" ]

[source]
url = "https://github.com/rodamaral/$(PACKAGE)/archive/refs/tags/v$(VERSION).zip"
dev = "git+https://github.com/rodamaral/$(PACKAGE).git"
dir = "$(PACKAGE)-$(VERSION)"

[dependencies]
inspect = "==2.0-1"
lua-cjson = "==2.1.0.10-1"

[dependencies.argparse ]
version = "==0.7.1-1"
pin = true
# Add your dependencies here
# `busted = ">=2.0"`

[run]
args = [ "src/main.lua" ]

[build]
type = "builtin"

[build.modules]
"luxdummy2" = "src/main.lua"
